package service

// Automatically generated by genmodel utility. DO NOT EDIT!

import (
	"errors"
	"time"

	"github.com/builderscon/octav/octav/db"
	"github.com/builderscon/octav/octav/model"
	"github.com/lestrrat/go-pdebug"
)

var _ = time.Time{}

// Create takes in the transaction, the incoming payload, and a reference to
// a database row. The database row is initialized/populated so that the
// caller can use it afterwards
func (v *Client) Create(tx *db.Tx, vdb *db.Client, payload model.CreateClientRequest) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker("service.Client.Create").BindError(&err)
		defer g.End()
	}

	if err := v.populateRowForCreate(vdb, payload); err != nil {
		return err
	}

	if err := vdb.Create(tx); err != nil {
		return err
	}

	return nil
}

func (v *Client) Update(tx *db.Tx, vdb *db.Client, payload model.UpdateClientRequest) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker("service.Client.Update (%s)", vdb.EID).BindError(&err)
		defer g.End()
	}

	if vdb.EID == "" {
		return errors.New("vdb.EID is required (did you forget to call vdb.Load(tx) before hand?)")
	}

	if err := v.populateRowForUpdate(vdb, payload); err != nil {
		return err
	}

	if err := vdb.Update(tx); err != nil {
		return err
	}
	return nil
}

func (v *Client) Delete(tx *db.Tx, id string) error {
	if pdebug.Enabled {
		g := pdebug.Marker("Client.Delete (%s)", id)
		defer g.End()
	}

	vdb := db.Client{EID: id}
	if err := vdb.Delete(tx); err != nil {
		return err
	}
	return nil
}

func (v *Client) LoadList(tx *db.Tx, vdbl *db.ClientList, since string, limit int) error {
	return vdbl.LoadSinceEID(tx, since, limit)
}
