package service

// Automatically generated by genmodel utility. DO NOT EDIT!

import (
	"context"
	"sync"
	"time"

	"github.com/builderscon/octav/octav/cache"

	"github.com/builderscon/octav/octav/db"
	"github.com/builderscon/octav/octav/internal/errors"
	"github.com/builderscon/octav/octav/model"
	"github.com/lestrrat/go-pdebug"
)

var _ = time.Time{}
var _ = cache.WithExpires(time.Minute)
var _ = context.Background
var _ = errors.Wrap
var _ = model.LocalizedString{}
var _ = db.LocalizedString{}
var _ = pdebug.Enabled

var localizedStringSvc LocalizedStringSvc
var localizedStringOnce sync.Once

func LocalizedString() *LocalizedStringSvc {
	localizedStringOnce.Do(localizedStringSvc.Init)
	return &localizedStringSvc
}
