package service

// Automatically generated by genmodel utility. DO NOT EDIT!

import (
	"sync"
	"time"

	"github.com/builderscon/octav/octav/db"
	"github.com/builderscon/octav/octav/model"
	"github.com/lestrrat/go-pdebug"
	"github.com/pkg/errors"
)

var _ = time.Time{}

var venueSvc *VenueSvc
var venueOnce sync.Once

func Venue() *VenueSvc {
	venueOnce.Do(venueSvc.Init)
	return venueSvc
}

func (v *VenueSvc) LookupFromPayload(tx *db.Tx, m *model.Venue, payload model.LookupVenueRequest) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker("service.Venue.LookupFromPayload").BindError(&err)
		defer g.End()
	}
	if err = v.Lookup(tx, m, payload.ID); err != nil {
		return errors.Wrap(err, "failed to load model.Venue from database")
	}
	if err := v.Decorate(tx, m, payload.TrustedCall, payload.Lang.String); err != nil {
		return errors.Wrap(err, "failed to load associated data for model.Venue from database")
	}
	return nil
}
func (v *VenueSvc) Lookup(tx *db.Tx, m *model.Venue, id string) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker("service.Venue.Lookup").BindError(&err)
		defer g.End()
	}

	r := model.Venue{}
	if err = r.Load(tx, id); err != nil {
		return errors.Wrap(err, "failed to load model.Venue from database")
	}
	*m = r
	return nil
}

// Create takes in the transaction, the incoming payload, and a reference to
// a database row. The database row is initialized/populated so that the
// caller can use it afterwards.
func (v *VenueSvc) Create(tx *db.Tx, vdb *db.Venue, payload model.CreateVenueRequest) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker("service.Venue.Create").BindError(&err)
		defer g.End()
	}

	if err := v.populateRowForCreate(vdb, payload); err != nil {
		return err
	}

	if err := vdb.Create(tx); err != nil {
		return err
	}

	if err := payload.L10N.CreateLocalizedStrings(tx, "Venue", vdb.EID); err != nil {
		return err
	}
	return nil
}

func (v *VenueSvc) Update(tx *db.Tx, vdb *db.Venue, payload model.UpdateVenueRequest) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker("service.Venue.Update (%s)", vdb.EID).BindError(&err)
		defer g.End()
	}

	if vdb.EID == "" {
		return errors.New("vdb.EID is required (did you forget to call vdb.Load(tx) before hand?)")
	}

	if err := v.populateRowForUpdate(vdb, payload); err != nil {
		return err
	}

	if err := vdb.Update(tx); err != nil {
		return err
	}

	return payload.L10N.Foreach(func(l, k, x string) error {
		if pdebug.Enabled {
			pdebug.Printf("Updating l10n string for '%s' (%s)", k, l)
		}
		ls := db.LocalizedString{
			ParentType: "Venue",
			ParentID:   vdb.EID,
			Language:   l,
			Name:       k,
			Localized:  x,
		}
		return ls.Upsert(tx)
	})
}

func (v *VenueSvc) ReplaceL10NStrings(tx *db.Tx, m *model.Venue, lang string) error {
	if pdebug.Enabled {
		g := pdebug.Marker("service.Venue.ReplaceL10NStrings lang = %s", lang)
		defer g.End()
	}
	switch lang {
	case "en":
		var vdb db.LocalizedString
		stmt, err := tx.Prepare(`SELECT localized FROM localized_strings WHERE parent_type = ? AND parent_id = ? AND name = ? AND language = ?`)
		if err != nil {
			return errors.Wrap(err, `failed to prepare query`)
		}
		if len(m.Name) == 0 {
			for _, lang := range []string{"ja"} {
				row := stmt.QueryRow("Venue", m.ID, "Name", lang)
				if err := row.Scan(&vdb); err != nil {
					if errors.IsSQLNoRows(err) {
						break
					}
					return errors.Wrap(err, `failed to scan row`)
				}
				m.Name = vdb.Localized
				break
			}
		}
		if len(m.Address) == 0 {
			for _, lang := range []string{"ja"} {
				row := stmt.QueryRow("Venue", m.ID, "Address", lang)
				if err := row.Scan(&vdb); err != nil {
					if errors.IsSQLNoRows(err) {
						break
					}
					return errors.Wrap(err, `failed to scan row`)
				}
				m.Address = vdb.Localized
				break
			}
		}
		return nil
	case "all":
		rows, err := tx.Query(`SELECT oid, parent_id, parent_type, name, language, localized FROM localized_strings WHERE parent_type = ? AND parent_id = ?`, "Venue", m.ID)
		if err != nil {
			return err
		}

		var l db.LocalizedString
		for rows.Next() {
			if err := l.Scan(rows); err != nil {
				return err
			}
			if len(l.Localized) == 0 {
				continue
			}
			if pdebug.Enabled {
				pdebug.Printf("Adding key '%s#%s'", l.Name, l.Language)
			}
			m.LocalizedFields.Set(l.Language, l.Name, l.Localized)
		}
	default:
		rows, err := tx.Query(`SELECT oid, parent_id, parent_type, name, language, localized FROM localized_strings WHERE parent_type = ? AND parent_id = ? AND language = ?`, "Venue", m.ID, lang)
		if err != nil {
			return err
		}

		var l db.LocalizedString
		for rows.Next() {
			if err := l.Scan(rows); err != nil {
				return err
			}
			if len(l.Localized) == 0 {
				continue
			}

			switch l.Name {
			case "name":
				if pdebug.Enabled {
					pdebug.Printf("Replacing for key 'name'")
				}
				m.Name = l.Localized
			case "address":
				if pdebug.Enabled {
					pdebug.Printf("Replacing for key 'address'")
				}
				m.Address = l.Localized
			}
		}
	}
	return nil
}

func (v *VenueSvc) Delete(tx *db.Tx, id string) error {
	if pdebug.Enabled {
		g := pdebug.Marker("Venue.Delete (%s)", id)
		defer g.End()
	}

	vdb := db.Venue{EID: id}
	if err := vdb.Delete(tx); err != nil {
		return err
	}
	if err := db.DeleteLocalizedStringsForParent(tx, id, "Venue"); err != nil {
		return err
	}
	return nil
}

func (v *VenueSvc) LoadList(tx *db.Tx, vdbl *db.VenueList, since string, limit int) error {
	return vdbl.LoadSinceEID(tx, since, limit)
}
