language: go
go:
  - 1.6
services:
  - mysql
env:
  - TEST_DIR=octav
  - TEST_DIR=adminweb
  - TEST_DIR=slackbot
addons:
  apt:
    packages:
      - cpanminus
      - perl
install:
  - echo "skipping install step"
script:
  - cd $TEST_DIR && ./travis.sh
after_failure:
  - test -e "/tmp/debug.out" && cat "/tmp/debug.out"
