language: go
go:
  - 1.8.x
services:
  - mysql
  - redis-server
env:
  - TEST_DIR=octav
addons:
  apt:
    packages:
      - cpanminus
      - perl
install:
  - echo "skipping install step"
script:
  - cd $TEST_DIR && ./travis.sh
after_failure:
  - test -e "/tmp/debug.out" && cat "/tmp/debug.out"
