kind: ReplicationController
apiVersion: v1
metadata:
  name: adminweb
spec:
  replicas: 3
  selector:
    name: adminweb
    group: octav
  template:
    metadata:
      labels:
        name: adminweb
        group: octav
    spec:
      volumes:
        - name: github
          secret:
            secretName: github-dev
        - name: googlemaps
          secret:
            secretName: googlemaps-dev
        - name: h2o
          secret:
            secretName: adminweb-h2o-dev
        - name: ssl
          secret:
            secretName: admin-builderscon-io-20160407-121650
      containers:
        - image: asia.gcr.io/builderscon-1248/h2o
          name: proxy
          ports:
            - name: h2o-proxy-http
              containerPort: 80
              protocol: TCP
            - name: h2o-proxy-https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: h2o
              readOnly: true
              mountPath: /etc/h2o
            - name: ssl
              readOnly: true
              mountPath: /etc/ssl/certs
          args:
            - -c
            - /etc/h2o/h2o.conf
        - image: asia.gcr.io/builderscon-1248/adminweb:20160407.110952
          name: app
          ports:
            - containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /auth/
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 5
          env:
            - name: OCTAV_REDIS
              value: 10.96.2.9:6379
            - name: OCTAV_GITHUB_CLIENT_ID
              value: /github/id
            - name: OCTAV_GITHUB_CLIENT_SECRET
              value: /github/secret
            - name: OCTAV_GOOGLE_MAPS_API_KEY
              value: /googlemaps/apikey
          volumeMounts:
            - name: github
              readOnly: true
              mountPath: /github
            - name: googlemaps
              readOnly: true
              mountPath: /googlemaps

