kind: ReplicationController
apiVersion: v1
metadata:
  name: slackbot
spec:
  replicas: 1
  selector:
    name: slackbot
    group: octav
  template:
    metadata:
      labels:
        name: slackbot
        group: octav
    spec:
      volumes:
        - name: slack
          secret:
            secretName: slack-dev
      containers:
        - image: asia.gcr.io/builderscon-1248/slackbot:20160401.150029
          name: slackbot
          env:
            - name: SLACKBOT_API_TOKEN_FILE
              value: /slack/token
          volumeMounts:
            - name: slack
              readOnly: true
              mountPath: /slack