package db

// Automatically generated by gendb utility. DO NOT EDIT!

import (
	"bytes"
	"database/sql"
	"strconv"
	"time"

	"github.com/builderscon/octav/octav/tools"
	"github.com/lestrrat/go-pdebug"
	"github.com/pkg/errors"
)

const BlogEntryStdSelectColumns = "blog_entries.oid, blog_entries.eid, blog_entries.conference_id, blog_entries.url, blog_entries.urlhash, blog_entries.created_on, blog_entries.modified_on"
const BlogEntryTable = "blog_entries"

type BlogEntryList []BlogEntry

func (b *BlogEntry) Scan(scanner interface {
	Scan(...interface{}) error
}) error {
	return scanner.Scan(&b.OID, &b.EID, &b.ConferenceID, &b.URL, &b.URLHash, &b.CreatedOn, &b.ModifiedOn)
}

func init() {
	hooks = append(hooks, func() {
		stmt := tools.GetBuffer()
		defer tools.ReleaseBuffer(stmt)

		stmt.Reset()
		stmt.WriteString(`DELETE FROM `)
		stmt.WriteString(BlogEntryTable)
		stmt.WriteString(` WHERE oid = ?`)
		library.Register("sqlBlogEntryDeleteByOIDKey", stmt.String())

		stmt.Reset()
		stmt.WriteString(`UPDATE `)
		stmt.WriteString(BlogEntryTable)
		stmt.WriteString(` SET eid = ?, conference_id = ?, url = ?, urlhash = ? WHERE oid = ?`)
		library.Register("sqlBlogEntryUpdateByOIDKey", stmt.String())

		stmt.Reset()
		stmt.WriteString(`SELECT `)
		stmt.WriteString(BlogEntryStdSelectColumns)
		stmt.WriteString(` FROM `)
		stmt.WriteString(BlogEntryTable)
		stmt.WriteString(` WHERE `)
		stmt.WriteString(BlogEntryTable)
		stmt.WriteString(`.eid = ?`)
		library.Register("sqlBlogEntryLoadByEIDKey", stmt.String())

		stmt.Reset()
		stmt.WriteString(`DELETE FROM `)
		stmt.WriteString(BlogEntryTable)
		stmt.WriteString(` WHERE eid = ?`)
		library.Register("sqlBlogEntryDeleteByEIDKey", stmt.String())

		stmt.Reset()
		stmt.WriteString(`UPDATE `)
		stmt.WriteString(BlogEntryTable)
		stmt.WriteString(` SET eid = ?, conference_id = ?, url = ?, urlhash = ? WHERE eid = ?`)
		library.Register("sqlBlogEntryUpdateByEIDKey", stmt.String())
	})
}

func (b *BlogEntry) LoadByEID(tx *Tx, eid string) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker(`BlogEntry.LoadByEID %s`, eid).BindError(&err)
		defer g.End()
	}
	stmt, err := library.GetStmt("sqlBlogEntryLoadByEIDKey")
	if err != nil {
		return errors.Wrap(err, `failed to get statement`)
	}
	row := tx.Stmt(stmt).QueryRow(eid)
	if err := b.Scan(row); err != nil {
		return err
	}
	return nil
}

func (b *BlogEntry) Create(tx *Tx, opts ...InsertOption) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker("db.BlogEntry.Create").BindError(&err)
		defer g.End()
		pdebug.Printf("%#v", b)
	}
	if b.EID == "" {
		return errors.New("create: non-empty EID required")
	}

	b.CreatedOn = time.Now()
	doIgnore := false
	for _, opt := range opts {
		switch opt.(type) {
		case insertIgnoreOption:
			doIgnore = true
		}
	}

	stmt := bytes.Buffer{}
	stmt.WriteString("INSERT ")
	if doIgnore {
		stmt.WriteString("IGNORE ")
	}
	stmt.WriteString("INTO ")
	stmt.WriteString(BlogEntryTable)
	stmt.WriteString(` (eid, conference_id, url, urlhash, created_on, modified_on) VALUES (?, ?, ?, ?, ?, ?)`)
	result, err := tx.Exec(stmt.String(), b.EID, b.ConferenceID, b.URL, b.URLHash, b.CreatedOn, b.ModifiedOn)
	if err != nil {
		return err
	}

	lii, err := result.LastInsertId()
	if err != nil {
		return err
	}

	b.OID = lii
	return nil
}

func (b BlogEntry) Update(tx *Tx) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker(`BlogEntry.Update`).BindError(&err)
		defer g.End()
	}
	if b.OID != 0 {
		if pdebug.Enabled {
			pdebug.Printf(`Using OID (%d) as key`, b.OID)
		}
		stmt, err := library.GetStmt("sqlBlogEntryUpdateByOIDKey")
		if err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		_, err = tx.Stmt(stmt).Exec(b.EID, b.ConferenceID, b.URL, b.URLHash, b.OID)
		return err
	}
	if b.EID != "" {
		if pdebug.Enabled {
			pdebug.Printf(`Using EID (%s) as key`, b.EID)
		}
		stmt, err := library.GetStmt("sqlBlogEntryUpdateByEIDKey")
		if err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		_, err = tx.Stmt(stmt).Exec(b.EID, b.ConferenceID, b.URL, b.URLHash, b.EID)
		return err
	}
	return errors.New("either OID/EID must be filled")
}

func (b BlogEntry) Delete(tx *Tx) error {
	if b.OID != 0 {
		stmt, err := library.GetStmt("sqlBlogEntryDeleteByOIDKey")
		if err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		_, err = tx.Stmt(stmt).Exec(b.OID)
		return err
	}

	if b.EID != "" {
		stmt, err := library.GetStmt("sqlBlogEntryDeleteByEIDKey")
		if err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		_, err = tx.Stmt(stmt).Exec(b.EID)
		return err
	}

	return errors.New("either OID/EID must be filled")
}

func (v *BlogEntryList) FromRows(rows *sql.Rows, capacity int) error {
	var res []BlogEntry
	if capacity > 0 {
		res = make([]BlogEntry, 0, capacity)
	} else {
		res = []BlogEntry{}
	}

	for rows.Next() {
		vdb := BlogEntry{}
		if err := vdb.Scan(rows); err != nil {
			return err
		}
		res = append(res, vdb)
	}
	*v = res
	return nil
}

func (v *BlogEntryList) LoadSinceEID(tx *Tx, since string, limit int) error {
	var s int64
	if id := since; id != "" {
		vdb := BlogEntry{}
		if err := vdb.LoadByEID(tx, id); err != nil {
			return err
		}

		s = vdb.OID
	}
	return v.LoadSince(tx, s, limit)
}

func (v *BlogEntryList) LoadSince(tx *Tx, since int64, limit int) error {
	rows, err := tx.Query(`SELECT `+BlogEntryStdSelectColumns+` FROM `+BlogEntryTable+` WHERE blog_entries.oid > ? ORDER BY oid ASC LIMIT `+strconv.Itoa(limit), since)
	if err != nil {
		return err
	}

	if err := v.FromRows(rows, limit); err != nil {
		return err
	}
	return nil
}
