package db

// Automatically generated by gendb utility. DO NOT EDIT!

import (
	"bytes"
	"database/sql"
	"errors"
	"time"
)

const ConferenceVenueStdSelectColumns = "conference_venues.oid, conference_venues.conference_id, conference_venues.venue_id, conference_venues.created_on, conference_venues.modified_on"
const ConferenceVenueTable = "conference_venues"

type ConferenceVenueList []ConferenceVenue

func (c *ConferenceVenue) Scan(scanner interface {
	Scan(...interface{}) error
}) error {
	return scanner.Scan(&c.OID, &c.ConferenceID, &c.VenueID, &c.CreatedOn, &c.ModifiedOn)
}

func (c *ConferenceVenue) Create(tx *Tx, opts ...InsertOption) error {
	c.CreatedOn = time.Now()
	doIgnore := false
	for _, opt := range opts {
		switch opt.(type) {
		case insertIgnoreOption:
			doIgnore = true
		}
	}

	stmt := bytes.Buffer{}
	stmt.WriteString("INSERT ")
	if doIgnore {
		stmt.WriteString("IGNORE ")
	}
	stmt.WriteString("INTO ")
	stmt.WriteString(ConferenceVenueTable)
	stmt.WriteString(` (conference_id, venue_id, created_on, modified_on) VALUES (?, ?, ?, ?)`)
	result, err := tx.Exec(stmt.String(), c.ConferenceID, c.VenueID, c.CreatedOn, c.ModifiedOn)
	if err != nil {
		return err
	}

	lii, err := result.LastInsertId()
	if err != nil {
		return err
	}

	c.OID = lii
	return nil
}

func (c ConferenceVenue) Update(tx *Tx) error {
	if c.OID != 0 {
		_, err := tx.Exec(`UPDATE `+ConferenceVenueTable+` SET conference_id = ?, venue_id = ? WHERE oid = ?`, c.ConferenceID, c.VenueID, c.OID)
		return err
	}
	return errors.New("either OID/EID must be filled")
}

func (c ConferenceVenue) Delete(tx *Tx) error {
	if c.OID != 0 {
		_, err := tx.Exec(`DELETE FROM `+ConferenceVenueTable+` WHERE oid = ?`, c.OID)
		return err
	}

	return errors.New("column OID must be filled")
}

func (v *ConferenceVenueList) FromRows(rows *sql.Rows, capacity int) error {
	var res []ConferenceVenue
	if capacity > 0 {
		res = make([]ConferenceVenue, 0, capacity)
	} else {
		res = []ConferenceVenue{}
	}

	for rows.Next() {
		vdb := ConferenceVenue{}
		if err := vdb.Scan(rows); err != nil {
			return err
		}
		res = append(res, vdb)
	}
	*v = res
	return nil
}
