package db

// Automatically generated by gendb utility. DO NOT EDIT!

import (
	"bytes"
	"database/sql"
	"strconv"
	"time"

	"github.com/builderscon/octav/octav/tools"
	"github.com/lestrrat/go-pdebug"
	"github.com/pkg/errors"
)

const QuestionStdSelectColumns = "questions.oid, questions.eid, questions.session_id, questions.user_id, questions.body, questions.created_on, questions.modified_on"
const QuestionTable = "questions"

type QuestionList []Question

func (q *Question) Scan(scanner interface {
	Scan(...interface{}) error
}) error {
	return scanner.Scan(&q.OID, &q.EID, &q.SessionID, &q.UserID, &q.Body, &q.CreatedOn, &q.ModifiedOn)
}

func init() {
	hooks = append(hooks, func() {
		stmt := tools.GetBuffer()
		defer tools.ReleaseBuffer(stmt)

		stmt.Reset()
		stmt.WriteString(`DELETE FROM `)
		stmt.WriteString(QuestionTable)
		stmt.WriteString(` WHERE oid = ?`)
		library.Register("sqlQuestionDeleteByOIDKey", stmt.String())

		stmt.Reset()
		stmt.WriteString(`UPDATE `)
		stmt.WriteString(QuestionTable)
		stmt.WriteString(` SET eid = ?, session_id = ?, user_id = ?, body = ? WHERE oid = ?`)
		library.Register("sqlQuestionUpdateByOIDKey", stmt.String())

		stmt.Reset()
		stmt.WriteString(`SELECT `)
		stmt.WriteString(QuestionStdSelectColumns)
		stmt.WriteString(` FROM `)
		stmt.WriteString(QuestionTable)
		stmt.WriteString(` WHERE `)
		stmt.WriteString(QuestionTable)
		stmt.WriteString(`.eid = ?`)
		library.Register("sqlQuestionLoadByEIDKey", stmt.String())

		stmt.Reset()
		stmt.WriteString(`DELETE FROM `)
		stmt.WriteString(QuestionTable)
		stmt.WriteString(` WHERE eid = ?`)
		library.Register("sqlQuestionDeleteByEIDKey", stmt.String())

		stmt.Reset()
		stmt.WriteString(`UPDATE `)
		stmt.WriteString(QuestionTable)
		stmt.WriteString(` SET eid = ?, session_id = ?, user_id = ?, body = ? WHERE eid = ?`)
		library.Register("sqlQuestionUpdateByEIDKey", stmt.String())
	})
}

func (q *Question) LoadByEID(tx *Tx, eid string) error {
	stmt, err := library.GetStmt("sqlQuestionLoadByEIDKey")
	if err != nil {
		return errors.Wrap(err, `failed to get statement`)
	}
	row := tx.Stmt(stmt).QueryRow(eid)
	if err := q.Scan(row); err != nil {
		return err
	}
	return nil
}

func (q *Question) Create(tx *Tx, opts ...InsertOption) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker("db.Question.Create").BindError(&err)
		defer g.End()
		pdebug.Printf("%#v", q)
	}
	if q.EID == "" {
		return errors.New("create: non-empty EID required")
	}

	q.CreatedOn = time.Now()
	doIgnore := false
	for _, opt := range opts {
		switch opt.(type) {
		case insertIgnoreOption:
			doIgnore = true
		}
	}

	stmt := bytes.Buffer{}
	stmt.WriteString("INSERT ")
	if doIgnore {
		stmt.WriteString("IGNORE ")
	}
	stmt.WriteString("INTO ")
	stmt.WriteString(QuestionTable)
	stmt.WriteString(` (eid, session_id, user_id, body, created_on, modified_on) VALUES (?, ?, ?, ?, ?, ?)`)
	result, err := tx.Exec(stmt.String(), q.EID, q.SessionID, q.UserID, q.Body, q.CreatedOn, q.ModifiedOn)
	if err != nil {
		return err
	}

	lii, err := result.LastInsertId()
	if err != nil {
		return err
	}

	q.OID = lii
	return nil
}

func (q Question) Update(tx *Tx) error {
	if q.OID != 0 {
		stmt, err := library.GetStmt("sqlQuestionUpdateByOIDKey")
		if err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		_, err = tx.Stmt(stmt).Exec(q.EID, q.SessionID, q.UserID, q.Body, q.OID)
		return err
	}
	if q.EID != "" {
		stmt, err := library.GetStmt("sqlQuestionUpdateByEIDKey")
		if err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		_, err = tx.Stmt(stmt).Exec(q.EID, q.SessionID, q.UserID, q.Body, q.EID)
		return err
	}
	return errors.New("either OID/EID must be filled")
}

func (q Question) Delete(tx *Tx) error {
	if q.OID != 0 {
		stmt, err := library.GetStmt("sqlQuestionDeleteByOIDKey")
		if err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		_, err = tx.Stmt(stmt).Exec(q.OID)
		return err
	}

	if q.EID != "" {
		stmt, err := library.GetStmt("sqlQuestionDeleteByEIDKey")
		if err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		_, err = tx.Stmt(stmt).Exec(q.EID)
		return err
	}

	return errors.New("either OID/EID must be filled")
}

func (v *QuestionList) FromRows(rows *sql.Rows, capacity int) error {
	var res []Question
	if capacity > 0 {
		res = make([]Question, 0, capacity)
	} else {
		res = []Question{}
	}

	for rows.Next() {
		vdb := Question{}
		if err := vdb.Scan(rows); err != nil {
			return err
		}
		res = append(res, vdb)
	}
	*v = res
	return nil
}

func (v *QuestionList) LoadSinceEID(tx *Tx, since string, limit int) error {
	var s int64
	if id := since; id != "" {
		vdb := Question{}
		if err := vdb.LoadByEID(tx, id); err != nil {
			return err
		}

		s = vdb.OID
	}
	return v.LoadSince(tx, s, limit)
}

func (v *QuestionList) LoadSince(tx *Tx, since int64, limit int) error {
	rows, err := tx.Query(`SELECT `+QuestionStdSelectColumns+` FROM `+QuestionTable+` WHERE questions.oid > ? ORDER BY oid ASC LIMIT `+strconv.Itoa(limit), since)
	if err != nil {
		return err
	}

	if err := v.FromRows(rows, limit); err != nil {
		return err
	}
	return nil
}
