// Automatically generated by gendb utility. DO NOT EDIT!
package db

import (
	"errors"
)

var RoomTable = "rooms"

func (r *Room) Scan(scanner interface {
	Scan(...interface{}) error
}) error {
	return scanner.Scan(&r.OID, &r.EID, &r.VenueID, &r.Name, &r.Capacity, &r.CreatedOn, &r.ModifiedOn)
}

func (r *Room) LoadByEID(tx *Tx, eid string) error {
	row := tx.QueryRow(`SELECT oid, eid, venue_id, name, capacity, created_on, modified_on FROM `+SessionTable+` WHERE eid = ?`, eid)
	if err := r.Scan(row); err != nil {
		return err
	}
	return nil
}

func (r *Room) Create(tx *Tx) error {
	if r.EID == "" {
		return errors.New("create: non-empty EID required")
	}

	result, err := tx.Exec(`INSERT INTO eid, venue_id, name, capacity, created_on, modified_on VALUES (?, ?, ?, ?, ?, ?)`, r.EID, r.VenueID, r.Name, r.Capacity, r.CreatedOn, r.ModifiedOn)
	if err != nil {
		return err
	}

	lii, err := result.LastInsertId()
	if err != nil {
		return err
	}

	r.OID = lii
	return nil
}
