package db

// Automatically generated by gendb utility. DO NOT EDIT!

import (
	"bytes"
	"database/sql"
	"strconv"
	"time"

	"github.com/lestrrat/go-pdebug"
	"github.com/pkg/errors"
)

const RoomStdSelectColumns = "rooms.oid, rooms.eid, rooms.venue_id, rooms.name, rooms.capacity, rooms.created_on, rooms.modified_on"
const RoomTable = "rooms"

type RoomList []Room

func (r *Room) Scan(scanner interface {
	Scan(...interface{}) error
}) error {
	return scanner.Scan(&r.OID, &r.EID, &r.VenueID, &r.Name, &r.Capacity, &r.CreatedOn, &r.ModifiedOn)
}

func (r *Room) LoadByEID(tx *sql.Tx, eid string) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker(`Room.LoadByEID %s`, eid).BindError(&err)
		defer g.End()
	}
	const sqltext = `SELECT rooms.oid, rooms.eid, rooms.venue_id, rooms.name, rooms.capacity, rooms.created_on, rooms.modified_on FROM rooms WHERE rooms.eid = ?`
	row, err := QueryRow(tx, sqltext, eid)
	if err != nil {
		return errors.Wrap(err, `failed to query row`)
	}
	if err := r.Scan(row); err != nil {
		return err
	}
	return nil
}

func (r *Room) Create(tx *sql.Tx, opts ...InsertOption) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker("db.Room.Create").BindError(&err)
		defer g.End()
		pdebug.Printf("%#v", r)
	}
	if r.EID == "" {
		return errors.New("create: non-empty EID required")
	}

	r.CreatedOn = time.Now()
	doIgnore := false
	for _, opt := range opts {
		switch opt.(type) {
		case insertIgnoreOption:
			doIgnore = true
		}
	}

	stmt := bytes.Buffer{}
	stmt.WriteString("INSERT ")
	if doIgnore {
		stmt.WriteString("IGNORE ")
	}
	stmt.WriteString("INTO ")
	stmt.WriteString(RoomTable)
	stmt.WriteString(` (eid, venue_id, name, capacity, created_on, modified_on) VALUES (?, ?, ?, ?, ?, ?)`)
	result, err := Exec(tx, stmt.String(), r.EID, r.VenueID, r.Name, r.Capacity, r.CreatedOn, r.ModifiedOn)
	if err != nil {
		return errors.Wrap(err, `failed to execute statement`)
	}

	lii, err := result.LastInsertId()
	if err != nil {
		return errors.Wrap(err, `failed to fetch last insert ID`)
	}

	r.OID = lii
	return nil
}

func (r Room) Update(tx *sql.Tx) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker(`Room.Update`).BindError(&err)
		defer g.End()
	}
	if r.OID != 0 {
		if pdebug.Enabled {
			pdebug.Printf(`Using OID (%d) as key`, r.OID)
		}
		const sqltext = `UPDATE rooms SET eid = ?, venue_id = ?, name = ?, capacity = ? WHERE oid = ?`
		if _, err := Exec(tx, sqltext, r.EID, r.VenueID, r.Name, r.Capacity, r.OID); err != nil {
			return errors.Wrap(err, `failed to execute statement`)
		}
		return nil
	}

	if r.EID != "" {
		if pdebug.Enabled {
			pdebug.Printf(`Using EID (%s) as key`, r.EID)
		}
		const sqltext = `UPDATE rooms SET eid = ?, venue_id = ?, name = ?, capacity = ? WHERE eid = ?`
		if _, err := Exec(tx, sqltext, r.EID, r.VenueID, r.Name, r.Capacity, r.EID); err != nil {
			return errors.Wrap(err, `failed to execute statement`)
		}
		return nil
	}
	return errors.New("either OID/EID must be filled")
}

func (r Room) Delete(tx *sql.Tx) error {
	if r.OID != 0 {
		const sqltext = `DELETE FROM rooms WHERE oid = ?`
		if _, err := Exec(tx, sqltext, r.OID); err != nil {
			return errors.Wrap(err, `failed to execute statement`)
		}
		return nil
	}

	if r.EID != "" {
		const sqltext = `DELETE FROM rooms WHERE eid = ?`
		if _, err := Exec(tx, sqltext, r.EID); err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		return nil
	}
	return errors.New("either OID/EID must be filled")
}

func (v *RoomList) FromRows(rows *sql.Rows, capacity int) error {
	var res []Room
	if capacity > 0 {
		res = make([]Room, 0, capacity)
	} else {
		res = []Room{}
	}

	for rows.Next() {
		vdb := Room{}
		if err := vdb.Scan(rows); err != nil {
			return err
		}
		res = append(res, vdb)
	}
	*v = res
	return nil
}

func (v *RoomList) LoadSinceEID(tx *sql.Tx, since string, limit int) error {
	var s int64
	if id := since; id != "" {
		vdb := Room{}
		if err := vdb.LoadByEID(tx, id); err != nil {
			return err
		}

		s = vdb.OID
	}
	return v.LoadSince(tx, s, limit)
}

func (v *RoomList) LoadSince(tx *sql.Tx, since int64, limit int) error {
	rows, err := Query(tx, `SELECT `+RoomStdSelectColumns+` FROM `+RoomTable+` WHERE rooms.oid > ? ORDER BY oid ASC LIMIT `+strconv.Itoa(limit), since)
	if err != nil {
		return err
	}
	defer rows.Close()

	if err := v.FromRows(rows, limit); err != nil {
		return err
	}
	return nil
}
