package db

// Automatically generated by gendb utility. DO NOT EDIT!

import (
	"bytes"
	"database/sql"
	"strconv"
	"time"

	"github.com/builderscon/octav/octav/tools"
	"github.com/lestrrat/go-pdebug"
	"github.com/pkg/errors"
)

const TrackStdSelectColumns = "tracks.oid, tracks.eid, tracks.conference_id, tracks.room_id, tracks.name, tracks.sort_order, tracks.created_on, tracks.modified_on"
const TrackTable = "tracks"

type TrackList []Track

func (t *Track) Scan(scanner interface {
	Scan(...interface{}) error
}) error {
	return scanner.Scan(&t.OID, &t.EID, &t.ConferenceID, &t.RoomID, &t.Name, &t.SortOrder, &t.CreatedOn, &t.ModifiedOn)
}

func init() {
	hooks = append(hooks, func() {
		stmt := tools.GetBuffer()
		defer tools.ReleaseBuffer(stmt)

		stmt.Reset()
		stmt.WriteString(`DELETE FROM `)
		stmt.WriteString(TrackTable)
		stmt.WriteString(` WHERE oid = ?`)
		library.Register("sqlTrackDeleteByOIDKey", stmt.String())

		stmt.Reset()
		stmt.WriteString(`UPDATE `)
		stmt.WriteString(TrackTable)
		stmt.WriteString(` SET eid = ?, conference_id = ?, room_id = ?, name = ?, sort_order = ? WHERE oid = ?`)
		library.Register("sqlTrackUpdateByOIDKey", stmt.String())

		stmt.Reset()
		stmt.WriteString(`SELECT `)
		stmt.WriteString(TrackStdSelectColumns)
		stmt.WriteString(` FROM `)
		stmt.WriteString(TrackTable)
		stmt.WriteString(` WHERE `)
		stmt.WriteString(TrackTable)
		stmt.WriteString(`.eid = ?`)
		library.Register("sqlTrackLoadByEIDKey", stmt.String())

		stmt.Reset()
		stmt.WriteString(`DELETE FROM `)
		stmt.WriteString(TrackTable)
		stmt.WriteString(` WHERE eid = ?`)
		library.Register("sqlTrackDeleteByEIDKey", stmt.String())

		stmt.Reset()
		stmt.WriteString(`UPDATE `)
		stmt.WriteString(TrackTable)
		stmt.WriteString(` SET eid = ?, conference_id = ?, room_id = ?, name = ?, sort_order = ? WHERE eid = ?`)
		library.Register("sqlTrackUpdateByEIDKey", stmt.String())
	})
}

func (t *Track) LoadByEID(tx *sql.Tx, eid string) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker(`Track.LoadByEID %s`, eid).BindError(&err)
		defer g.End()
	}
	stmt, err := library.GetStmt("sqlTrackLoadByEIDKey")
	if err != nil {
		return errors.Wrap(err, `failed to get statement`)
	}
	row := tx.Stmt(stmt).QueryRow(eid)
	if err := t.Scan(row); err != nil {
		return err
	}
	return nil
}

func (t *Track) Create(tx *sql.Tx, opts ...InsertOption) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker("db.Track.Create").BindError(&err)
		defer g.End()
		pdebug.Printf("%#v", t)
	}
	if t.EID == "" {
		return errors.New("create: non-empty EID required")
	}

	t.CreatedOn = time.Now()
	doIgnore := false
	for _, opt := range opts {
		switch opt.(type) {
		case insertIgnoreOption:
			doIgnore = true
		}
	}

	stmt := bytes.Buffer{}
	stmt.WriteString("INSERT ")
	if doIgnore {
		stmt.WriteString("IGNORE ")
	}
	stmt.WriteString("INTO ")
	stmt.WriteString(TrackTable)
	stmt.WriteString(` (eid, conference_id, room_id, name, sort_order, created_on, modified_on) VALUES (?, ?, ?, ?, ?, ?, ?)`)
	result, err := tx.Exec(stmt.String(), t.EID, t.ConferenceID, t.RoomID, t.Name, t.SortOrder, t.CreatedOn, t.ModifiedOn)
	if err != nil {
		return err
	}

	lii, err := result.LastInsertId()
	if err != nil {
		return err
	}

	t.OID = lii
	return nil
}

func (t Track) Update(tx *sql.Tx) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker(`Track.Update`).BindError(&err)
		defer g.End()
	}
	if t.OID != 0 {
		if pdebug.Enabled {
			pdebug.Printf(`Using OID (%d) as key`, t.OID)
		}
		stmt, err := library.GetStmt("sqlTrackUpdateByOIDKey")
		if err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		_, err = tx.Stmt(stmt).Exec(t.EID, t.ConferenceID, t.RoomID, t.Name, t.SortOrder, t.OID)
		return err
	}
	if t.EID != "" {
		if pdebug.Enabled {
			pdebug.Printf(`Using EID (%s) as key`, t.EID)
		}
		stmt, err := library.GetStmt("sqlTrackUpdateByEIDKey")
		if err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		_, err = tx.Stmt(stmt).Exec(t.EID, t.ConferenceID, t.RoomID, t.Name, t.SortOrder, t.EID)
		return err
	}
	return errors.New("either OID/EID must be filled")
}

func (t Track) Delete(tx *sql.Tx) error {
	if t.OID != 0 {
		stmt, err := library.GetStmt("sqlTrackDeleteByOIDKey")
		if err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		_, err = tx.Stmt(stmt).Exec(t.OID)
		return err
	}

	if t.EID != "" {
		stmt, err := library.GetStmt("sqlTrackDeleteByEIDKey")
		if err != nil {
			return errors.Wrap(err, `failed to get statement`)
		}
		_, err = tx.Stmt(stmt).Exec(t.EID)
		return err
	}

	return errors.New("either OID/EID must be filled")
}

func (v *TrackList) FromRows(rows *sql.Rows, capacity int) error {
	var res []Track
	if capacity > 0 {
		res = make([]Track, 0, capacity)
	} else {
		res = []Track{}
	}

	for rows.Next() {
		vdb := Track{}
		if err := vdb.Scan(rows); err != nil {
			return err
		}
		res = append(res, vdb)
	}
	*v = res
	return nil
}

func (v *TrackList) LoadSinceEID(tx *sql.Tx, since string, limit int) error {
	var s int64
	if id := since; id != "" {
		vdb := Track{}
		if err := vdb.LoadByEID(tx, id); err != nil {
			return err
		}

		s = vdb.OID
	}
	return v.LoadSince(tx, s, limit)
}

func (v *TrackList) LoadSince(tx *sql.Tx, since int64, limit int) error {
	rows, err := tx.Query(`SELECT `+TrackStdSelectColumns+` FROM `+TrackTable+` WHERE tracks.oid > ? ORDER BY oid ASC LIMIT `+strconv.Itoa(limit), since)
	if err != nil {
		return err
	}

	if err := v.FromRows(rows, limit); err != nil {
		return err
	}
	return nil
}
