apiVersion: v1
kind: Service
metadata:
    name: apiserver
    labels:
        name: apiserver
spec:
    type: LoadBalancer
    selector:
        name: apiserver
    ports:
        - name: apiserver
          port: 8080