apiVersion: v1
kind: Service
metadata:
    name: adminweb
    labels:
        name: adminweb
spec:
    type: LoadBalancer
    selector:
        name: adminweb
    ports:
        - name: adminweb
          port: 5000