apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: octav-slackgw-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: slackgw
        group: octav
    spec:
      volumes:
        - name: slack
          secret:
            secretName: slack-dev
        - name: google
          secret:
            secretName: google-dev
        - name: k8s-certupload
          emptyDir:
            medium: Memory
      containers:
        # Talks to slack, accepts requests to post to slack
        - image: asia.gcr.io/builderscon-1248/slackgw:20160418.134603
          name: slackgw
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - name: http
              containerPort: 4979
              protocol: TCP
          args:
            - -listen
            - 0.0.0.0:4979
            - -rtm
            - gpubsub-forward
            - -gpubsub-forward.project_id
            - builderscon-1248
            - -gpubsub-forward.event
            - MessageEvent
            - -gpubsub-forward.topic
            - slackgw-forward
            - -tokenfile
            - /slack/token
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /google/servicekey
          volumeMounts:
            - name: google
              readOnly: true
              mountPath: /google
            - name: slack
              readOnly: true
              mountPath: /slack
        # Listens to google pubsub, routes the messages to the
        # appropriate worker
        - image: asia.gcr.io/builderscon-1248/slackrouter:20160419.120729
          name: slackrouter
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          args:
            - -project_id
            - builderscon-1248
            - -slackgw
            - http://slackgw:4979
            - -topic
            - slacgw-subscribe
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /google/servicekey
          volumeMounts:
            - name: google
              readOnly: true
              mountPath: /google
        # Listens to google pubsub, does the acme stuff
        - image: asia.gcr.io/builderscon-1248/acmebot:20160418.164337
          name: acmebot
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          args:
            - -email
            - lestrrat@gmail.com
            - -fifopath
            - /k8s-certupload/fifo
            - -project_id
            - builderscon-1248
            - -slackgw
            - http://slackgw:4979
            - -topic
            - acmebot-subscribe
            - -zone
            - builderscon
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /google/servicekey
          volumeMounts:
            - name: google
              readOnly: true
              mountPath: /google
            - name: k8s-certupload
              readOnly: false
              mountPath: /k8s-certupload
        # Auxilary tool to listen to fifo and push secrets to k8s
        - image: asia.gcr.io/builderscon-1248/acmebot-k8s-certupload:20160418.164051
          name: acmebot-k8s-certupload
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          args:
            - -slackgw
            - http://slackgw:4979
            - -fifopath
            - /k8s-certupload/fifo
          volumeMounts:
            - name: k8s-certupload
              readOnly: false
              mountPath: /k8s-certupload

