package model

// Automatically generated by genmodel utility. DO NOT EDIT!

import (
	"time"

	"github.com/builderscon/octav/octav/db"
	"github.com/lestrrat/go-pdebug"
)

var _ = pdebug.Enabled
var _ = time.Time{}

func (v *ConferenceVenue) ToRow(vdb *db.ConferenceVenue) error {
	vdb.ConferenceID = v.ConferenceID
	vdb.VenueID = v.VenueID
	return nil
}
